// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "k2c_affine_matmul.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic k2c_affine_matmul::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic k2c_affine_matmul::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state1 = "1";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state2 = "10";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state3 = "100";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state4 = "1000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state5 = "10000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state6 = "100000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state7 = "1000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state8 = "10000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state9 = "100000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state10 = "1000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state11 = "10000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state12 = "100000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<24> k2c_affine_matmul::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_A = "1010";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_11 = "10001";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_F = "1111";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_16 = "10110";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_1 = "1";
const sc_lv<1> k2c_affine_matmul::ap_const_lv1_0 = "0";
const sc_lv<1> k2c_affine_matmul::ap_const_lv1_1 = "1";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_2 = "10";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_3 = "11";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_4 = "100";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_5 = "101";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_6 = "110";
const sc_lv<64> k2c_affine_matmul::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<7> k2c_affine_matmul::ap_const_lv7_0 = "0000000";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_17 = "10111";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_10 = "10000";
const sc_lv<12> k2c_affine_matmul::ap_const_lv12_0 = "000000000000";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_9 = "1001";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_B = "1011";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_12 = "10010";
const sc_lv<32> k2c_affine_matmul::ap_const_lv32_7 = "111";
const sc_lv<64> k2c_affine_matmul::ap_const_lv64_1 = "1";
const sc_lv<7> k2c_affine_matmul::ap_const_lv7_1 = "1";
const bool k2c_affine_matmul::ap_const_boolean_1 = true;

k2c_affine_matmul::k2c_affine_matmul(sc_module_name name) : sc_module(name), mVcdFile(0) {
    check_best_model_cud_U37 = new check_best_model_cud<1,5,32,32,32>("check_best_model_cud_U37");
    check_best_model_cud_U37->clk(ap_clk);
    check_best_model_cud_U37->reset(ap_rst);
    check_best_model_cud_U37->din0(reg_190);
    check_best_model_cud_U37->din1(grp_fu_182_p1);
    check_best_model_cud_U37->ce(ap_var_for_const0);
    check_best_model_cud_U37->dout(grp_fu_182_p2);
    check_best_model_dEe_U38 = new check_best_model_dEe<1,4,32,32,32>("check_best_model_dEe_U38");
    check_best_model_dEe_U38->clk(ap_clk);
    check_best_model_dEe_U38->reset(ap_rst);
    check_best_model_dEe_U38->din0(A_load_reg_490);
    check_best_model_dEe_U38->din1(B_load_reg_495);
    check_best_model_dEe_U38->ce(ap_var_for_const0);
    check_best_model_dEe_U38->dout(grp_fu_186_p2);
    check_best_model_kbM_U39 = new check_best_model_kbM<1,1,8,13,13>("check_best_model_kbM_U39");
    check_best_model_kbM_U39->din0(tmp_fu_350_p0);
    check_best_model_kbM_U39->din1(tmp_fu_350_p1);
    check_best_model_kbM_U39->dout(tmp_fu_350_p2);
    check_best_model_kbM_U40 = new check_best_model_kbM<1,1,8,13,13>("check_best_model_kbM_U40");
    check_best_model_kbM_U40->din0(outrowidx_fu_355_p0);
    check_best_model_kbM_U40->din1(tmp_29_fu_254_p1);
    check_best_model_kbM_U40->dout(outrowidx_fu_355_p2);
    check_best_model_kbM_U41 = new check_best_model_kbM<1,1,8,13,13>("check_best_model_kbM_U41");
    check_best_model_kbM_U41->din0(inneridx_fu_360_p0);
    check_best_model_kbM_U41->din1(tmp_29_fu_254_p1);
    check_best_model_kbM_U41->dout(inneridx_fu_360_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sum5_cast_fu_330_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sum8_cast_fu_345_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_C_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( C_addr_2_reg_457 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( sum_cast_fu_249_p1 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_C_d0);
    sensitive << ( reg_195 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond3_fu_233_p2 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( ap_CS_fsm_state17 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_258_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_258_p2 );

    SC_METHOD(thread_col_2_fu_238_p2);
    sensitive << ( col_reg_127 );

    SC_METHOD(thread_col_cast5_fu_225_p1);
    sensitive << ( col_reg_127 );

    SC_METHOD(thread_col_cast_fu_229_p1);
    sensitive << ( col_reg_127 );

    SC_METHOD(thread_d_address0);
    sensitive << ( j_cast2_reg_444 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_d_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_exitcond1_fu_285_p2);
    sensitive << ( outcols );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j_cast_fu_281_p1 );

    SC_METHOD(thread_exitcond2_fu_258_p2);
    sensitive << ( outrows );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_exitcond3_fu_233_p2);
    sensitive << ( outcols );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( col_cast_fu_229_p1 );

    SC_METHOD(thread_exitcond4_fu_208_p2);
    sensitive << ( outrows );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_116 );

    SC_METHOD(thread_exitcond_fu_314_p2);
    sensitive << ( innerdim );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( k_cast_fu_310_p1 );

    SC_METHOD(thread_grp_fu_182_p1);
    sensitive << ( tmp_5_reg_500 );
    sensitive << ( d_load_reg_505 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_i_19_fu_263_p2);
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_innerdim_cast_fu_219_p1);
    sensitive << ( innerdim );

    SC_METHOD(thread_inneridx_fu_360_p0);
    sensitive << ( innerdim_cast_reg_403 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_j_7_fu_290_p2);
    sensitive << ( j_reg_149 );

    SC_METHOD(thread_j_cast2_fu_277_p1);
    sensitive << ( j_reg_149 );

    SC_METHOD(thread_j_cast3_fu_273_p1);
    sensitive << ( j_reg_149 );

    SC_METHOD(thread_j_cast4_fu_269_p1);
    sensitive << ( j_reg_149 );

    SC_METHOD(thread_j_cast_fu_281_p1);
    sensitive << ( j_reg_149 );

    SC_METHOD(thread_k_2_fu_319_p2);
    sensitive << ( k_reg_160 );

    SC_METHOD(thread_k_cast1_fu_306_p1);
    sensitive << ( k_reg_160 );

    SC_METHOD(thread_k_cast_fu_310_p1);
    sensitive << ( k_reg_160 );

    SC_METHOD(thread_next_mul_fu_335_p2);
    sensitive << ( tmp_4_reg_408 );
    sensitive << ( phi_mul_reg_171 );

    SC_METHOD(thread_outcols_cast8_fu_200_p1);
    sensitive << ( outcols );

    SC_METHOD(thread_outrowidx_fu_355_p0);
    sensitive << ( outcols_cast8_reg_384 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_row_2_fu_213_p2);
    sensitive << ( row_reg_116 );

    SC_METHOD(thread_sum2_cast_fu_301_p1);
    sensitive << ( sum2_fu_296_p2 );

    SC_METHOD(thread_sum2_fu_296_p2);
    sensitive << ( outrowidx_reg_429 );
    sensitive << ( j_cast3_fu_273_p1 );

    SC_METHOD(thread_sum5_cast_fu_330_p1);
    sensitive << ( sum5_fu_325_p2 );

    SC_METHOD(thread_sum5_fu_325_p2);
    sensitive << ( inneridx_reg_434 );
    sensitive << ( k_cast1_fu_306_p1 );

    SC_METHOD(thread_sum8_cast_fu_345_p1);
    sensitive << ( sum8_fu_340_p2 );

    SC_METHOD(thread_sum8_fu_340_p2);
    sensitive << ( j_cast4_reg_439 );
    sensitive << ( phi_mul_reg_171 );

    SC_METHOD(thread_sum_cast_fu_249_p1);
    sensitive << ( sum_fu_244_p2 );

    SC_METHOD(thread_sum_fu_244_p2);
    sensitive << ( tmp_reg_398 );
    sensitive << ( col_cast5_fu_225_p1 );

    SC_METHOD(thread_tmp_29_fu_254_p1);
    sensitive << ( i_reg_138 );

    SC_METHOD(thread_tmp_4_fu_222_p1);
    sensitive << ( outcols );

    SC_METHOD(thread_tmp_fu_350_p0);
    sensitive << ( outcols_cast8_reg_384 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_fu_350_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_116 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond4_fu_208_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond2_fu_258_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond1_fu_285_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond_fu_314_p2 );
    sensitive << ( exitcond3_fu_233_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "k2c_affine_matmul_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
    sc_trace(mVcdFile, C_q0, "(port)C_q0");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, d_address0, "(port)d_address0");
    sc_trace(mVcdFile, d_ce0, "(port)d_ce0");
    sc_trace(mVcdFile, d_q0, "(port)d_q0");
    sc_trace(mVcdFile, outrows, "(port)outrows");
    sc_trace(mVcdFile, outcols, "(port)outcols");
    sc_trace(mVcdFile, innerdim, "(port)innerdim");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_190, "reg_190");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_fu_182_p2, "grp_fu_182_p2");
    sc_trace(mVcdFile, reg_195, "reg_195");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, outcols_cast8_fu_200_p1, "outcols_cast8_fu_200_p1");
    sc_trace(mVcdFile, outcols_cast8_reg_384, "outcols_cast8_reg_384");
    sc_trace(mVcdFile, row_2_fu_213_p2, "row_2_fu_213_p2");
    sc_trace(mVcdFile, row_2_reg_393, "row_2_reg_393");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_350_p2, "tmp_fu_350_p2");
    sc_trace(mVcdFile, tmp_reg_398, "tmp_reg_398");
    sc_trace(mVcdFile, exitcond4_fu_208_p2, "exitcond4_fu_208_p2");
    sc_trace(mVcdFile, innerdim_cast_fu_219_p1, "innerdim_cast_fu_219_p1");
    sc_trace(mVcdFile, innerdim_cast_reg_403, "innerdim_cast_reg_403");
    sc_trace(mVcdFile, tmp_4_fu_222_p1, "tmp_4_fu_222_p1");
    sc_trace(mVcdFile, tmp_4_reg_408, "tmp_4_reg_408");
    sc_trace(mVcdFile, col_2_fu_238_p2, "col_2_fu_238_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_19_fu_263_p2, "i_19_fu_263_p2");
    sc_trace(mVcdFile, i_19_reg_424, "i_19_reg_424");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, outrowidx_fu_355_p2, "outrowidx_fu_355_p2");
    sc_trace(mVcdFile, outrowidx_reg_429, "outrowidx_reg_429");
    sc_trace(mVcdFile, exitcond2_fu_258_p2, "exitcond2_fu_258_p2");
    sc_trace(mVcdFile, inneridx_fu_360_p2, "inneridx_fu_360_p2");
    sc_trace(mVcdFile, inneridx_reg_434, "inneridx_reg_434");
    sc_trace(mVcdFile, j_cast4_fu_269_p1, "j_cast4_fu_269_p1");
    sc_trace(mVcdFile, j_cast4_reg_439, "j_cast4_reg_439");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, j_cast2_fu_277_p1, "j_cast2_fu_277_p1");
    sc_trace(mVcdFile, j_cast2_reg_444, "j_cast2_reg_444");
    sc_trace(mVcdFile, j_7_fu_290_p2, "j_7_fu_290_p2");
    sc_trace(mVcdFile, j_7_reg_452, "j_7_reg_452");
    sc_trace(mVcdFile, C_addr_2_reg_457, "C_addr_2_reg_457");
    sc_trace(mVcdFile, exitcond1_fu_285_p2, "exitcond1_fu_285_p2");
    sc_trace(mVcdFile, k_2_fu_319_p2, "k_2_fu_319_p2");
    sc_trace(mVcdFile, k_2_reg_465, "k_2_reg_465");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, exitcond_fu_314_p2, "exitcond_fu_314_p2");
    sc_trace(mVcdFile, next_mul_fu_335_p2, "next_mul_fu_335_p2");
    sc_trace(mVcdFile, next_mul_reg_475, "next_mul_reg_475");
    sc_trace(mVcdFile, A_load_reg_490, "A_load_reg_490");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, B_load_reg_495, "B_load_reg_495");
    sc_trace(mVcdFile, grp_fu_186_p2, "grp_fu_186_p2");
    sc_trace(mVcdFile, tmp_5_reg_500, "tmp_5_reg_500");
    sc_trace(mVcdFile, d_load_reg_505, "d_load_reg_505");
    sc_trace(mVcdFile, row_reg_116, "row_reg_116");
    sc_trace(mVcdFile, exitcond3_fu_233_p2, "exitcond3_fu_233_p2");
    sc_trace(mVcdFile, col_reg_127, "col_reg_127");
    sc_trace(mVcdFile, i_reg_138, "i_reg_138");
    sc_trace(mVcdFile, j_reg_149, "j_reg_149");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, k_reg_160, "k_reg_160");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, phi_mul_reg_171, "phi_mul_reg_171");
    sc_trace(mVcdFile, sum_cast_fu_249_p1, "sum_cast_fu_249_p1");
    sc_trace(mVcdFile, sum2_cast_fu_301_p1, "sum2_cast_fu_301_p1");
    sc_trace(mVcdFile, sum5_cast_fu_330_p1, "sum5_cast_fu_330_p1");
    sc_trace(mVcdFile, sum8_cast_fu_345_p1, "sum8_cast_fu_345_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_182_p1, "grp_fu_182_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, col_cast_fu_229_p1, "col_cast_fu_229_p1");
    sc_trace(mVcdFile, col_cast5_fu_225_p1, "col_cast5_fu_225_p1");
    sc_trace(mVcdFile, sum_fu_244_p2, "sum_fu_244_p2");
    sc_trace(mVcdFile, j_cast_fu_281_p1, "j_cast_fu_281_p1");
    sc_trace(mVcdFile, j_cast3_fu_273_p1, "j_cast3_fu_273_p1");
    sc_trace(mVcdFile, sum2_fu_296_p2, "sum2_fu_296_p2");
    sc_trace(mVcdFile, k_cast_fu_310_p1, "k_cast_fu_310_p1");
    sc_trace(mVcdFile, k_cast1_fu_306_p1, "k_cast1_fu_306_p1");
    sc_trace(mVcdFile, sum5_fu_325_p2, "sum5_fu_325_p2");
    sc_trace(mVcdFile, sum8_fu_340_p2, "sum8_fu_340_p2");
    sc_trace(mVcdFile, tmp_fu_350_p0, "tmp_fu_350_p0");
    sc_trace(mVcdFile, tmp_fu_350_p1, "tmp_fu_350_p1");
    sc_trace(mVcdFile, outrowidx_fu_355_p0, "outrowidx_fu_355_p0");
    sc_trace(mVcdFile, tmp_29_fu_254_p1, "tmp_29_fu_254_p1");
    sc_trace(mVcdFile, inneridx_fu_360_p0, "inneridx_fu_360_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

k2c_affine_matmul::~k2c_affine_matmul() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete check_best_model_cud_U37;
    delete check_best_model_dEe_U38;
    delete check_best_model_kbM_U39;
    delete check_best_model_kbM_U40;
    delete check_best_model_kbM_U41;
}

void k2c_affine_matmul::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void k2c_affine_matmul::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_208_p2.read(), ap_const_lv1_0))) {
        col_reg_127 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(exitcond3_fu_233_p2.read(), ap_const_lv1_0))) {
        col_reg_127 = col_2_fu_238_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_285_p2.read(), ap_const_lv1_1))) {
        i_reg_138 = i_19_reg_424.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond4_fu_208_p2.read(), ap_const_lv1_1))) {
        i_reg_138 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        j_reg_149 = j_7_reg_452.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_258_p2.read(), ap_const_lv1_0))) {
        j_reg_149 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_285_p2.read(), ap_const_lv1_0))) {
        k_reg_160 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        k_reg_160 = k_2_reg_465.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_285_p2.read(), ap_const_lv1_0))) {
        phi_mul_reg_171 = ap_const_lv12_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        phi_mul_reg_171 = next_mul_reg_475.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_233_p2.read(), ap_const_lv1_1))) {
        row_reg_116 = row_2_reg_393.read();
    } else if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        row_reg_116 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        A_load_reg_490 = A_q0.read();
        B_load_reg_495 = B_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond1_fu_285_p2.read(), ap_const_lv1_0))) {
        C_addr_2_reg_457 =  (sc_lv<12>) (sum2_cast_fu_301_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        d_load_reg_505 = d_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_19_reg_424 = i_19_fu_263_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond4_fu_208_p2.read(), ap_const_lv1_1))) {
        innerdim_cast_reg_403 = innerdim_cast_fu_219_p1.read();
        tmp_4_reg_408 = tmp_4_fu_222_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond2_fu_258_p2.read(), ap_const_lv1_0))) {
        inneridx_reg_434 = inneridx_fu_360_p2.read();
        outrowidx_reg_429 = outrowidx_fu_355_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        j_7_reg_452 = j_7_fu_290_p2.read();
        j_cast2_reg_444 = j_cast2_fu_277_p1.read();
        j_cast4_reg_439 = j_cast4_fu_269_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        k_2_reg_465 = k_2_fu_319_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(exitcond_fu_314_p2.read(), ap_const_lv1_0))) {
        next_mul_reg_475 = next_mul_fu_335_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        outcols_cast8_reg_384 = outcols_cast8_fu_200_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        reg_190 = C_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        reg_195 = grp_fu_182_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_2_reg_393 = row_2_fu_213_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        tmp_5_reg_500 = grp_fu_186_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond4_fu_208_p2.read(), ap_const_lv1_0))) {
        tmp_reg_398 = tmp_fu_350_p2.read();
    }
}

void k2c_affine_matmul::thread_A_address0() {
    A_address0 =  (sc_lv<12>) (sum5_cast_fu_330_p1.read());
}

void k2c_affine_matmul::thread_A_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void k2c_affine_matmul::thread_B_address0() {
    B_address0 =  (sc_lv<12>) (sum8_cast_fu_345_p1.read());
}

void k2c_affine_matmul::thread_B_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void k2c_affine_matmul::thread_C_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        C_address0 = C_addr_2_reg_457.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        C_address0 =  (sc_lv<12>) (sum_cast_fu_249_p1.read());
    } else {
        C_address0 = "XXXXXXXXXXXX";
    }
}

void k2c_affine_matmul::thread_C_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void k2c_affine_matmul::thread_C_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        C_d0 = reg_195.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        C_d0 = ap_const_lv32_0;
    } else {
        C_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void k2c_affine_matmul::thread_C_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(exitcond3_fu_233_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void k2c_affine_matmul::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void k2c_affine_matmul::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void k2c_affine_matmul::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_258_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void k2c_affine_matmul::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void k2c_affine_matmul::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_258_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void k2c_affine_matmul::thread_col_2_fu_238_p2() {
    col_2_fu_238_p2 = (!col_reg_127.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(col_reg_127.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void k2c_affine_matmul::thread_col_cast5_fu_225_p1() {
    col_cast5_fu_225_p1 = esl_zext<13,7>(col_reg_127.read());
}

void k2c_affine_matmul::thread_col_cast_fu_229_p1() {
    col_cast_fu_229_p1 = esl_zext<8,7>(col_reg_127.read());
}

void k2c_affine_matmul::thread_d_address0() {
    d_address0 =  (sc_lv<12>) (j_cast2_reg_444.read());
}

void k2c_affine_matmul::thread_d_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        d_ce0 = ap_const_logic_1;
    } else {
        d_ce0 = ap_const_logic_0;
    }
}

void k2c_affine_matmul::thread_exitcond1_fu_285_p2() {
    exitcond1_fu_285_p2 = (!j_cast_fu_281_p1.read().is_01() || !outcols.read().is_01())? sc_lv<1>(): sc_lv<1>(j_cast_fu_281_p1.read() == outcols.read());
}

void k2c_affine_matmul::thread_exitcond2_fu_258_p2() {
    exitcond2_fu_258_p2 = (!i_reg_138.read().is_01() || !outrows.read().is_01())? sc_lv<1>(): sc_lv<1>(i_reg_138.read() == outrows.read());
}

void k2c_affine_matmul::thread_exitcond3_fu_233_p2() {
    exitcond3_fu_233_p2 = (!col_cast_fu_229_p1.read().is_01() || !outcols.read().is_01())? sc_lv<1>(): sc_lv<1>(col_cast_fu_229_p1.read() == outcols.read());
}

void k2c_affine_matmul::thread_exitcond4_fu_208_p2() {
    exitcond4_fu_208_p2 = (!row_reg_116.read().is_01() || !outrows.read().is_01())? sc_lv<1>(): sc_lv<1>(row_reg_116.read() == outrows.read());
}

void k2c_affine_matmul::thread_exitcond_fu_314_p2() {
    exitcond_fu_314_p2 = (!k_cast_fu_310_p1.read().is_01() || !innerdim.read().is_01())? sc_lv<1>(): sc_lv<1>(k_cast_fu_310_p1.read() == innerdim.read());
}

void k2c_affine_matmul::thread_grp_fu_182_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        grp_fu_182_p1 = d_load_reg_505.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        grp_fu_182_p1 = tmp_5_reg_500.read();
    } else {
        grp_fu_182_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void k2c_affine_matmul::thread_i_19_fu_263_p2() {
    i_19_fu_263_p2 = (!ap_const_lv64_1.is_01() || !i_reg_138.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(i_reg_138.read()));
}

void k2c_affine_matmul::thread_innerdim_cast_fu_219_p1() {
    innerdim_cast_fu_219_p1 = esl_zext<13,8>(innerdim.read());
}

void k2c_affine_matmul::thread_inneridx_fu_360_p0() {
    inneridx_fu_360_p0 =  (sc_lv<8>) (innerdim_cast_reg_403.read());
}

void k2c_affine_matmul::thread_j_7_fu_290_p2() {
    j_7_fu_290_p2 = (!j_reg_149.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(j_reg_149.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void k2c_affine_matmul::thread_j_cast2_fu_277_p1() {
    j_cast2_fu_277_p1 = esl_zext<64,7>(j_reg_149.read());
}

void k2c_affine_matmul::thread_j_cast3_fu_273_p1() {
    j_cast3_fu_273_p1 = esl_zext<13,7>(j_reg_149.read());
}

void k2c_affine_matmul::thread_j_cast4_fu_269_p1() {
    j_cast4_fu_269_p1 = esl_zext<12,7>(j_reg_149.read());
}

void k2c_affine_matmul::thread_j_cast_fu_281_p1() {
    j_cast_fu_281_p1 = esl_zext<8,7>(j_reg_149.read());
}

void k2c_affine_matmul::thread_k_2_fu_319_p2() {
    k_2_fu_319_p2 = (!k_reg_160.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(k_reg_160.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void k2c_affine_matmul::thread_k_cast1_fu_306_p1() {
    k_cast1_fu_306_p1 = esl_zext<13,7>(k_reg_160.read());
}

void k2c_affine_matmul::thread_k_cast_fu_310_p1() {
    k_cast_fu_310_p1 = esl_zext<8,7>(k_reg_160.read());
}

void k2c_affine_matmul::thread_next_mul_fu_335_p2() {
    next_mul_fu_335_p2 = (!phi_mul_reg_171.read().is_01() || !tmp_4_reg_408.read().is_01())? sc_lv<12>(): (sc_biguint<12>(phi_mul_reg_171.read()) + sc_biguint<12>(tmp_4_reg_408.read()));
}

void k2c_affine_matmul::thread_outcols_cast8_fu_200_p1() {
    outcols_cast8_fu_200_p1 = esl_zext<13,8>(outcols.read());
}

void k2c_affine_matmul::thread_outrowidx_fu_355_p0() {
    outrowidx_fu_355_p0 =  (sc_lv<8>) (outcols_cast8_reg_384.read());
}

void k2c_affine_matmul::thread_row_2_fu_213_p2() {
    row_2_fu_213_p2 = (!ap_const_lv64_1.is_01() || !row_reg_116.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(row_reg_116.read()));
}

void k2c_affine_matmul::thread_sum2_cast_fu_301_p1() {
    sum2_cast_fu_301_p1 = esl_zext<64,13>(sum2_fu_296_p2.read());
}

void k2c_affine_matmul::thread_sum2_fu_296_p2() {
    sum2_fu_296_p2 = (!j_cast3_fu_273_p1.read().is_01() || !outrowidx_reg_429.read().is_01())? sc_lv<13>(): (sc_biguint<13>(j_cast3_fu_273_p1.read()) + sc_bigint<13>(outrowidx_reg_429.read()));
}

void k2c_affine_matmul::thread_sum5_cast_fu_330_p1() {
    sum5_cast_fu_330_p1 = esl_zext<64,13>(sum5_fu_325_p2.read());
}

void k2c_affine_matmul::thread_sum5_fu_325_p2() {
    sum5_fu_325_p2 = (!inneridx_reg_434.read().is_01() || !k_cast1_fu_306_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(inneridx_reg_434.read()) + sc_biguint<13>(k_cast1_fu_306_p1.read()));
}

void k2c_affine_matmul::thread_sum8_cast_fu_345_p1() {
    sum8_cast_fu_345_p1 = esl_zext<64,12>(sum8_fu_340_p2.read());
}

void k2c_affine_matmul::thread_sum8_fu_340_p2() {
    sum8_fu_340_p2 = (!j_cast4_reg_439.read().is_01() || !phi_mul_reg_171.read().is_01())? sc_lv<12>(): (sc_biguint<12>(j_cast4_reg_439.read()) + sc_biguint<12>(phi_mul_reg_171.read()));
}

void k2c_affine_matmul::thread_sum_cast_fu_249_p1() {
    sum_cast_fu_249_p1 = esl_zext<64,13>(sum_fu_244_p2.read());
}

void k2c_affine_matmul::thread_sum_fu_244_p2() {
    sum_fu_244_p2 = (!col_cast5_fu_225_p1.read().is_01() || !tmp_reg_398.read().is_01())? sc_lv<13>(): (sc_biguint<13>(col_cast5_fu_225_p1.read()) + sc_bigint<13>(tmp_reg_398.read()));
}

void k2c_affine_matmul::thread_tmp_29_fu_254_p1() {
    tmp_29_fu_254_p1 = i_reg_138.read().range(13-1, 0);
}

void k2c_affine_matmul::thread_tmp_4_fu_222_p1() {
    tmp_4_fu_222_p1 = esl_zext<12,8>(outcols.read());
}

void k2c_affine_matmul::thread_tmp_fu_350_p0() {
    tmp_fu_350_p0 =  (sc_lv<8>) (outcols_cast8_reg_384.read());
}

void k2c_affine_matmul::thread_tmp_fu_350_p1() {
    tmp_fu_350_p1 = row_reg_116.read().range(13-1, 0);
}

void k2c_affine_matmul::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond4_fu_208_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond3_fu_233_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond2_fu_258_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond1_fu_285_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(exitcond_fu_314_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

